# 2025-09-19 knowpd

grafana-k8s-monitoring:
  cluster:
    name: aks-demo
  
  destinations:
    - name: grafanacloud
      type: prometheus
      url: https://prometheus-prod-56-prod-us-east-2.grafana.net/api/prom/push
      basicAuth:
        username: 2634121
        # will override at install time
        password: ${GRAFANA_CLOUD_API_TOKEN}
  
  # REQUIRED: enable the metrics collector (Grafana Alloy)
  alloy-metrics:
    enabled: true
    controller:
      podAnnotations:
        kubernetes.azure.com/set-kube-service-host-fqdn: "true"   # AKS requirement
  
  # Cluster metrics (KSM, node exporter, kubelet/cAdvisor, API server, etc.)
  clusterMetrics:
    enabled: true
    # (optional but harmless) keep it on KSM too, some older validations asked for this:
    kube-state-metrics:
      podAnnotations:
        kubernetes.azure.com/set-kube-service-host-fqdn: "true"
  
  # Minimal: no logs/traces/profiles
  podLogs:
    enabled: false
  nodeLogs:
    enabled: false
  applicationObservability:
    enabled: false
  profiles:
    enabled: false
